FROM node:20 AS build
WORKDIR /app
COPY packages/client/package.json .
RUN yarn install
COPY packages/client .

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

RUN yarn build
 
