name: Build and Deploy

on:
  push:
    branches:
      - main
      - test/CICD
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/corinee-server-v2 -f ./dockerfile-server-v2 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/corinee-server-v2
          docker build --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} -t ${{ secrets.DOCKERHUB_USERNAME }}/corinee-client-v2 -f ./dockerfile-client-v2 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/corinee-client-v2

      - name: Make main server environment
        run: |
          echo "${{ secrets.DEPLOY_ENV }}" > .env
  
      - name: Send files & deploy script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml,nginx.conf,.env"
          target: /corinee-v2
          overwrite: true

      - name: Deploy to main server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /corinee-v2
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/corinee-server-v2
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/corinee-client-v2
            docker-compose down
            docker-compose up -d
            docker image prune -f
